version: 1
update_configs:
  - package_manager: python
    directory: /
    update_schedule: live
    default_reviewers:
      - "totvslabs/ai"
    default_assignees:
      - "totvslabsbot"
    default_labels:
      - "difficulty/easy"
      - "kind/bug"
      - "priority/medium"
    commit_message:
      prefix: "fix"
      include_scope: true
